# Generated by Django 5.1 on 2025-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event_created_at_event_updated_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default='2025-04-27 23:59:59'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default='2025-04-24 00:00:00'),
        ),
    ]
