# Generated by Django 5.1 on 2025-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_event_date_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default='2025-04-27'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2025-04-24'),
        ),
    ]
