# Generated by Django 5.1 on 2025-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_event_end_time_event_start_time_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='emails_of_additional_attendees',
        ),
        migrations.AddField(
            model_name='registration',
            name='additional_adults',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='additional_kids',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
