# Generated by Django 5.1 on 2025-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_additional_kids_registration_additional_kids_3_8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='selected_meals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
