# Generated by Django 5.1 on 2025-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_registration_selected_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
