[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt", 
    "**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
# Run database migrations after the build and before starting the app
postDeployCommand = "python manage.py migrate --no-input"
